import '@mantine/core/styles.css'
import Footer from './_components/Footer'
import Header from './_components/Header/Header'
import { ColorSchemeScript, MantineProvider } from '@mantine/core'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider defaultColorScheme="dark">
          <Header />
          {children}
          <Footer />
        </MantineProvider>
      </body>
    </html>
  )
}
