import "@mantine/core/styles.css";
import Footer from "./_components/Footer";
import Header from "./_components/Headers/Header";
import type { AppProps } from "next/app";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { styles } from "./main-styles.module.scss";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<head>
				<ColorSchemeScript />
			</head>
			<body>
				<MantineProvider defaultColorScheme="dark">
					<Header />
					{children}
					<Footer />
				</MantineProvider>
			</body>
		</html>
	);
}
